### PR TITLE
Networking rewrite

### PR DESCRIPTION
**Pull request by Elinvynia**
Another huge PR, I had to rewrite the server representation to keep a vector of users instead of separate hashmaps indexed by userid. This will make everything much easier.

Also updated the representation to make it less error-prone.

### CODE REVIEW

**Comment by Elinvynia** [comment]
Finding: making send_map send just a single packet seems also borked. This is likely a clientside or a representation issue.
Sending another command like move, which also has data associated also causes no issues.
Will investigate the representation now.

**Comment by Elinvynia** [comment]
Update: Seems like the ser/de process is having issues with it being a tuple of 2 values instead of just one. Will look into the best way of fixing that (and likely slightly redesign the `packet` and `command`) !

**Comment by Elinvynia** [comment]
Should be good now :)

**Review by meesha7 — APPROVED** [review]
Wow that's a lotta work there, you've been pretty busy! Nice job :)

**Pull request merged**
